// Here we implement our methods that are generated by tscodegen.
// Every function gets the JSI runtime. For most methods we do not
// need this.

#include "react-native-bbs-signatures.h"

using namespace facebook;
using namespace react;

NativeBbsSignatures::NativeBbsSignatures(std::shared_ptr<CallInvoker> jsInvoker)
    : BbsSignaturesCxxSpecJSI(jsInvoker){};

double NativeBbsSignatures::multiply(jsi::Runtime &rt, double a, double b) {
  return a * b;
}
