/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 *
 * @generated by codegen project: GenerateModuleH.js
 */

#include <NativeModules.h>

namespace facebook {
namespace react {

static jsi::Value __hostFunction_BbsSignaturesCxxSpecJSI_multiply(
    jsi::Runtime &rt, TurboModule &turboModule, const jsi::Value *args,
    size_t count) {
  return static_cast<BbsSignaturesCxxSpecJSI *>(&turboModule)
      ->multiply(rt, args[0].getNumber(), args[1].getNumber());
}

BbsSignaturesCxxSpecJSI::BbsSignaturesCxxSpecJSI(
    std::shared_ptr<CallInvoker> jsInvoker)
    : TurboModule("BbsSignatures", jsInvoker) {
  methodMap_["multiply"] =
      MethodMetadata{2, __hostFunction_BbsSignaturesCxxSpecJSI_multiply};
}

} // namespace react
} // namespace facebook
